apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: proxy
  name: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  strategy: {}
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - args:
        - /bin/bash
        - -c
        - envsubst < /tmp/uwsgi_backend.conf > /etc/nginx/conf.d/new_config.conf &&
          cat /etc/nginx/conf.d/new_config.conf && nginx -g 'daemon off;'
        image: dipinthomas2003/nginx-proxy-uwsgi:latest
        env:
        - name: BB_HOST
          value: backend
        - name: BB_PORT
          value: "5000"
        name: proxy
        resources: {}
        ports:
        - containerPort: 5000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: proxy
  name: proxy
spec:
  ports:
  - nodePort: 5000
    name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    app: proxy
  type: NodePort